@startuml

Actor Frontend
node WebServer
component Laravel
component MariaDB
component Nginx
component Linux_SO

Frontend -> WebServer : http
WebServer -right-> Laravel : API REST
Laravel ..> MariaDB : use
WebServer .down.> Nginx : has
WebServer .down.> Linux_SO : has
WebServer .down.> MariaDB : has
@enduml
