@startuml

Actor Frontend
node WebServer
component TimeRegisterAPI <<API REST>>
component Laravel
component MariaDB
component Nginx
component Linux_SO

Frontend -> WebServer : http
WebServer -right-> TimeRegisterAPI 
TimeRegisterAPI .down.> Laravel : Framework
TimeRegisterAPI ..> MariaDB : Database
WebServer -down-> Nginx 
WebServer -down-> Linux_SO 
WebServer -down-> MariaDB 
WebServer -down-> Laravel
@enduml
