@startuml

class TimeRegister
class User
class Project 
class Category
class Interval {
  startTime
  endTime
  begin(project Project)
  begin()
  end()
}
class Customer

TimeRegister *-down-> "n" User
User *-down-> "n" Customer
Customer *-down-> "n" Project
User *-down-> "n" Category
Project *-down-> "n" Interval
Interval "n" o-down-> "n" Category

@enduml
