@startuml
left to right direction

actor User
usecase "List intervals" as List
usecase "Show interval" as Show
usecase "Open interval" as Open
usecase "Close interval" as Close
usecase "Update Interval" as Update
usecase "Delete Interval" as Delete
usecase "Attach Category" as Attach
usecase "Detach Category" as Detach

User --> List
User --> Show 
User --> Open
User --> Close
User --> Update
User --> Delete
User --> Attach
User --> Detach

Open ..> Show: include
Close ..> Show: include
Update ..> Show: include
@enduml
