@startuml
left to right direction

actor Frontend
usecase "IntervalList" as List
usecase "IntervalShow" as Show
usecase "IntervalOpen" as Open
usecase "IntervalClose" as Close
usecase "IntervalUpdate" as Update
usecase "IntervalDestroy" as Delete
usecase "UpdateIntervalCategory"

Frontend --> List
Frontend --> Show 
Frontend --> Open
Frontend --> Close
Frontend --> Update
Frontend --> Delete
Frontend --> UpdateIntervalCategory

Open ..> Show: include
Close ..> Show: include
Update ..> Show: include
@enduml
