@startuml
state Opened
Opened : Se trabaja en una tarea
state Closed
Closed: Se ha cerrado el intervalo abierto

[*] --> Closed
Opened -left-> Closed : Close interval
Closed -right-> Opened : Open interval


note right of Opened
  Solo es posible tener
  un intervalo de trabajo abierto
end note

@enduml